name: build_test

on:
  push:

jobs:

  build-back:
    runs-on: ubuntu-latest
    env:
      working-directory: ./back
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          args: --prefer-dist --no-progress --no-suggest
        working-directory: ${{ env.working-directory }}
      
      - name: PHPUnit
        uses: chindit/actions-phpunit-symfony@master
        working-directory: ${{ env.working-directory }}
          
  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16 
      - run: cd front && npm ci
      - run: cd front && npm run build
      - run: cd front && npm run test:unit
