name: build_test

on:
  push:

jobs:

  build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: cd back 

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      
      - name: PHPUnit
        uses: chindit/actions-phpunit-symfony@master

  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: cd front
      - run: npm ci
      - run: npm run build
      - run: npm test
