name: build_test

on:
  push:

jobs:

  build-back:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: baschny/php-composer-action@v2

      - name: Install dependencies
        run: cd back && composer install --prefer-dist --no-progress --no-suggest
      
      - name: PHPUnit
        uses: chindit/actions-phpunit-symfony@master

  build-front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16 
      - run: cd front && npm ci
      - run: cd front && npm run build
      - run: cd front && npm run test:unit
